### ISSUE TITLE
Fails to build using OpenSSL 4.0

### ISSUE THREAD

**Issue by Castaglia** [Castaglia/proftpd-mod_proxy#313]
The mod_proxy module currently fails to compile when using OpenSSL 4.0:
```
$ ./configure --with-modules=mod_sftp:mod_tls:mod_proxy
...
lib/proxy/tls.c:234:39: warning: passing 'const X509_NAME *' (aka 'const struct X509_name_st *') to parameter of type 'X509_NAME *' (aka 'struct X509_name_st *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  234 |     subj_name = tls_x509_name_oneline(X509_get_subject_name(cert));
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/proxy/tls.c:183:47: note: passing argument to parameter 'x509_name' here
  183 | static char *tls_x509_name_oneline(X509_NAME *x509_name) {
      |                                               ^
lib/proxy/tls.c:817:28: error: call to undeclared function 'ASN1_STRING_data'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  817 |         dns_san = (char *) ASN1_STRING_data(alt_name->d.ia5);
      |                            ^
lib/proxy/tls.c:817:19: warning: cast to 'char *' from smaller integer type 'int' [-Wint-to-pointer-cast]
  817 |         dns_san = (char *) ASN1_STRING_data(alt_name->d.ia5);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/proxy/tls.c:892:20: error: call to undeclared function 'ASN1_STRING_data'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  892 |         san_data = ASN1_STRING_data(alt_name->d.ip);
      |                    ^
lib/proxy/tls.c:892:18: error: incompatible integer to pointer conversion assigning to 'unsigned char *' from 'int' [-Wint-conversion]
  892 |         san_data = ASN1_STRING_data(alt_name->d.ip);
      |                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/proxy/tls.c:983:13: warning: assigning to 'X509_NAME *' (aka 'struct X509_name_st *') from 'const X509_NAME *' (aka 'const struct X509_name_st *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  983 |   subj_name = X509_get_subject_name(cert);
      |             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/proxy/tls.c:999:12: warning: assigning to 'X509_NAME_ENTRY *' (aka 'struct X509_name_entry_st *') from 'const X509_NAME_ENTRY *' (aka 'const struct X509_name_entry_st *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  999 |   cn_entry = X509_NAME_get_entry(subj_name, idx);
      |            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/proxy/tls.c:1009:11: warning: assigning to 'ASN1_STRING *' (aka 'struct asn1_string_st *') from 'const ASN1_STRING *' (aka 'const struct asn1_string_st *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
 1009 |   cn_asn1 = X509_NAME_ENTRY_get_data(cn_entry);
      |           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/proxy/tls.c:1018:21: error: call to undeclared function 'ASN1_STRING_data'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1018 |   cn_str = (char *) ASN1_STRING_data(cn_asn1);
      |                     ^
lib/proxy/tls.c:1018:12: warning: cast to 'char *' from smaller integer type 'int' [-Wint-to-pointer-cast]
 1018 |   cn_str = (char *) ASN1_STRING_data(cn_asn1);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/proxy/tls.c:1151:29: warning: passing 'const X509_NAME *' (aka 'const struct X509_name_st *') to parameter of type 'X509_NAME *' (aka 'struct X509_name_st *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
 1151 |       tls_x509_name_oneline(X509_get_subject_name(cert)));
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/proxy/tls.c:183:47: note: passing argument to parameter 'x509_name' here
  183 | static char *tls_x509_name_oneline(X509_NAME *x509_name) {
      |                                               ^
lib/proxy/tls.c:1154:29: warning: passing 'const X509_NAME *' (aka 'const struct X509_name_st *') to parameter of type 'X509_NAME *' (aka 'struct X509_name_st *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
 1154 |       tls_x509_name_oneline(X509_get_issuer_name(cert)));
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
lib/proxy/tls.c:183:47: note: passing argument to parameter 'x509_name' here
  183 | static char *tls_x509_name_oneline(X509_NAME *x509_name) {
      |                                               ^
lib/proxy/tls.c:1217:31: warning: passing 'const X509_NAME *' (aka 'const struct X509_name_st *') to parameter of type 'X509_NAME *' (aka 'struct X509_name_st *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
 1217 |         tls_x509_name_oneline(X509_get_subject_name(cert)));
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/proxy/tls.c:183:47: note: passing argument to parameter 'x509_name' here
  183 | static char *tls_x509_name_oneline(X509_NAME *x509_name) {
      |                                               ^
lib/proxy/tls.c:1220:31: warning: passing 'const X509_NAME *' (aka 'const struct X509_name_st *') to parameter of type 'X509_NAME *' (aka 'struct X509_name_st *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
 1220 |         tls_x509_name_oneline(X509_get_issuer_name(cert)));
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
lib/proxy/tls.c:183:47: note: passing argument to parameter 'x509_name' here
  183 | static char *tls_x509_name_oneline(X509_NAME *x509_name) {
      |                                               ^
10 warnings and 4 errors generated.
```

Several of the fixes from https://github.com/proftpd/proftpd/issues/2120 will need to be made in the mod_proxy codebase as well, I suspect.

**Comment by Castaglia** [comment]
Now fixed in master.
